pipeline{
 agent any
 
  tools{
    maven "mymaven"
  }
  environment{
        tomcatWebLocation="\"C:\\Program Files\\Apache Software Foundation\\Tomcat 9.0\\webapps\""
        tomcatBinLocation="\"C:\Program Files\Apache Software Foundation\Tomcat 9.0\\bin\""
        buildLocation="C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\pipeline_git_Jenkinsfile_tomcat\\mywebapp\\target\\mywebapp.war"
    }
  stages {
    stage('Git checkout'){
     steps{
     git "https://github.com/codewithz/dxc-web-app.git"
     
     }
    }
    stage('Maven Build'){
      steps{
       bat"""
        cd mywebapp
        mvn clean package
        """
      }
    }
  }
  post{
        success{
 
            bat """
                copy %buildLocation%  %tomcatWebLocation%
                
            """
 
        }
    }
}
