pipeline{
 agent any
  tools{
    maven "mymaven"
  }
  stages {
    stage('build'){
     steps{
     git "https://github.com/jenkins-docs/simple-java-maven-app.git"
     bat 'mvn clean package' 
     }
    }
  }
  
}
