pipeline{
 agent any
 environment{
  jarlocation='C:\\ProgramData\\Jenkins\\.jenkins\\workspace\\dxc_git_mave_Jenkinsfile\\target\\my-app-1.0-SNAPSHOT.jar'
 }
  tools{
    maven "mymaven"
  }
  stages {
    stage('build'){
     steps{
     git "https://github.com/jenkins-docs/simple-java-maven-app.git"
     bat 'mvn clean test package' 
     }
    }
  }
 post{
  sucess{
   bat 'java -jar %jarlocation%
  }
 }
}
